language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

branches:
  only:
  - master

install:
  - npm install hexo -g
  - npm install

script:
  - hexo cl
  - hexo g

branches:
  only:
    - hexo
