language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo

before_install:
  - npm install -g hexo
  - git clone https://github.com/theme-next/hexo-theme-next themes/uglyboy
  - cp -r themes/next/* themes/uglyboy/

before_script:
  - git config --global user.name 'uglyboy-tl'
  - git config --global user.email 'uglyboy@aliyun.com'
  - sed -i'' "s~git@github.com/uglyboy-tl/uglyboy-tl.github.io.git~https://${token}:x-oauth-basic@github.com/uglyboy-tl/uglyboy-tl.github.io.git~" _config.yml

install:
  - npm install


script:
  - hexo cl
  - hexo g

after_success:
  - hexo d
