language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

branches:
  only:
  - master

install:
  - npm install hexo -g
  - npm install
  - git clone https://github.com/theme-next/hexo-theme-next themes/next

script:
  - hexo cl
  - hexo g

branches:
  only:
    - hexo
